### ISSUE TITLE
期待跟新

### ISSUE THREAD

**Issue by yu910709** [pujiaxun/tax-it#1]
😂😂😂
恬不知耻的期待跟新以下feature
1.新的个税规则。
2.可以配置个税减免的项目。
3.联动税务系统查询实交个税额。

**Comment by pujiaxun** [comment]
@watanabeyu0709 从去年12月就打算更新来着，心想不就改改几个case…… 但当时没看懂新税法，刚刚发现还有人在star，我决定研究一下。。。 发现新税法是以年为单位累计，每月预扣税。这样的话列出单月的税额好像没什么参考意义，每个月都不一样。再加上新的减免政策，可变动的东西太多了。。用alfred不是很适合。再考虑不同地区的五险一金，我决定archive this repo了。。。

然后又看到你这个issue😂 我……
